services:
  api-gateway:
    container_name: api-gateway
    image: api-gateway-image
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:latest
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
